//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPSU
    {
        public int ID { get; set; }
        public Nullable<int> UPSModel { get; set; }
        public string SerialNum { get; set; }
        public string InvNum { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Stat Stat { get; set; }
        public virtual UPSMod UPSMod { get; set; }
    }
}
